name: Make Xposed Test Package

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: git clone -b ${GITHUB_REF_NAME} --recurse-submodules https://github.com/siavash79/AOSPMods.git .
        name: Grab source code
        
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant permission shell scripts
        run: chmod +x .github/*.sh

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Sign app APK

        id: sign_app
        run: |
          if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
            echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> keystore.properties
            echo keyAlias='${{ secrets.KEY_ALIAS }}' >> keystore.properties
            echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties
            echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties
            echo ${{ secrets.KEYSTORE }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi

      - name: Magisk Module Generation
        run: .github/make_debug_zip.sh
        
      - name: Upload APK file
        uses: actions/upload-artifact@v2
        with:
          name: PixelXpert_Xposed.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      - name: Upload Xposed Artifact to Actions
        uses: actions/upload-artifact@v2
        with: 
          name: AOSPMods_Xposed.zip
          path: output
