name: Make Xposed Test Package

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: git clone -b ${GITHUB_REF_NAME} --recurse-submodules https://github.com/siavash79/AOSPMods.git .
        name: Grab source code
        
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant permission shell scripts
        run: chmod +x .github/*.sh

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Upload Xposed Artifact to Actions
        uses: actions/upload-artifact@v2
        with: 
          name: AOSPMods_Xposed.zip
          path: output
